### Create a new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@example.com"
}

###

### List all users (should show the newly created user)
GET http://localhost:8080/users

###

### Create another user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@example.com"
}

###

### List all users (should show both users)
GET http://localhost:8080/users

###

### User 1 creates a new poll
POST http://localhost:8080/polls
Content-Type: application/json

{
  "question": "Is Java awesome?",
  "publishedAt": "2024-09-03T12:00:00Z",
  "validUntil": "2024-09-10T12:00:00Z",
  "username": "user1",
  "voteOption": [
    {"caption":  "Yes"},
    {"caption":  "No"}
  ]
}

###

### List polls (should show the new poll)
GET http://localhost:8080/polls

###

### User 2 votes on the poll
POST http://localhost:8080/polls/1/votes
Content-Type: application/json

{
  "pollID": "1",
  "username": "user2",
  "voteOption": {"caption": "Yes"}
}

###

### User 2 changes his vote
PUT http://localhost:8080/polls/1/votes
Content-Type: application/json

{
  "pollID": "1",
  "username": "user2",
  "voteOption": {"caption": "No"}
}

###

### List votes (should show the most recent vote for User 2)
GET http://localhost:8080/polls/1/votes

###

### Delete the one poll
DELETE http://localhost:8080/polls/1

###

### List votes (should be empty)
GET http://localhost:8080/polls/1/votes